name: CI

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          run_install: false

      # setup nodejs
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
          
      # setup rust
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-wasi
      - name: Set npm publish token
        run: echo -e //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH }}
      - name: Publish package
        run: npm publish

 
    
 
