name: CI

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          run_install: false

      # setup nodejs
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
          
      # setup rust
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-wasi

      - name: Install dependencies
        run: pnpm i

      - name: Build project
        run: pnpm build
      
      - name: Run tests
        run: pnpm test
